# Generated by Django 5.0.6 on 2024-06-17 08:50

import comments.models
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('home_page', models.URLField(blank=True, null=True, verbose_name='Home page')),
                ('text', models.TextField(verbose_name='Your comment')),
                ('file', models.FileField(blank=True, null=True, upload_to=comments.models.release_upload_to, verbose_name='Attach some file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
